---
# tasks file for roles/kind
- block:
  
  - name: install_kind
    shell:
      cmd: go install sigs.k8s.io/kind@{{kind_version}}
      creates: /home/{{ ansible_env.SUDO_USER }}/go/bin/kind

  - name: PATH
    lineinfile:
      path: /home/{{ ansible_env.SUDO_USER }}/.bashrc
      line: export PATH=$PATH:$HOME/go/bin

  - name: mkdir_kind
    file:
      path: /home/{{ ansible_env.SUDO_USER }}/Sources/kind_conf
      state: directory
      owner: "{{ ansible_env.SUDO_USER }}"
      group: "{{ ansible_env.SUDO_USER }}"

  - name: cluster_conf
    template:
      src: cluster-conf.yml.j2
      dest: /home/{{ ansible_env.SUDO_USER }}/Sources/kind_conf/cluster-conf.yml
      owner: "{{ ansible_env.SUDO_USER }}"
      group: "{{ ansible_env.SUDO_USER }}"
