---
# tasks file for roles/goland

- block:
  #- name: Get ansible_user home directory
  #  shell: 'getent passwd "{{ansible_env.SUDO_USER}}" | cut -d: -f6'
  #  register: ansible_home_result

  #- name: Set the fact for the other scripts to use
  #  set_fact: ansible_home='{{ansible_home_result.stdout}}'

  - name: mkdir_Downloads
    file:
      path: /home/{{ ansible_env.SUDO_USER }}/Downloads
      state: directory
      owner: "{{ ansible_env.SUDO_USER }}"
      group: "{{ ansible_env.SUDO_USER }}"
  - name: downloads_tar
    get_url:
      url: https://download.jetbrains.com/go/goland-{{ goland_version }}.tar.gz
      dest: /home/{{ ansible_env.SUDO_USER }}/Downloads/goland-{{ goland_version }}.tar.gz
      owner: "{{ ansible_env.SUDO_USER }}"
      group: "{{ ansible_env.SUDO_USER }}"
  - name: mkdir_goland
    file:
      path: /home/{{ ansible_env.SUDO_USER }}/GoLand
      state: directory
      owner: "{{ ansible_env.SUDO_USER }}"
      group: "{{ ansible_env.SUDO_USER }}"
  - name: unarchive_goland
    unarchive: 
      src: /home/{{ ansible_env.SUDO_USER }}/Downloads/goland-{{ goland_version }}.tar.gz
      dest: /home/{{ ansible_env.SUDO_USER }}/GoLand
      remote_src: yes
      owner: "{{ ansible_env.SUDO_USER }}"
      group: "{{ ansible_env.SUDO_USER }}"
      creates: "{{ansible_home}}/GoLand/GoLand-{{ goland_version }}"
  - name: configure_alternatives
    alternatives:
      name: goland
      path: "{{ansible_home}}/GoLand/GoLand-{{ goland_version }}/bin/goland.sh"
      link: "{{ansible_home}}/.local/bin/goland"
  - name: copy_ideavimrc
    get_url:
      url: https://raw.githubusercontent.com/dobachi/ideavimrc/master/_ideavimrc
      dest: "{{ansible_home}}/.ideavimrc"
    become: no

  tags:
    - goland
