- hosts: "{{ server | default('wsl') }}"
  roles:
    - register_home
    - hosts
    - rasp_dir_jp_eng
    - commons
    - ipafont
    - git
      #  #    - zed
    - tmux
    - vim
    - vim_config
    - gvim
    - keyboard_nocaps
      #- bash
      #- pip3
      #- pyenv
      #- intellij
      #- pycharm
      #- goland

# vim: et ts=2 sw=2:
