---
# tasks file for roles/samba

- block:

  - name: install samba
    package: name=samba state=present

  - name: configure smb.conf
    template: src=smb.conf.j2 dest=/etc/samba/smb.conf
    notify: restart smb

  - name: configure services
    service: name=smbd state=started enabled=yes

  tags:
    - samba
