galaxy_info:
  author: dobachi
  description: Install Quarto (open-source scientific & technical publishing system)
  license: BSD-3-Clause
  min_ansible_version: "2.9"
  galaxy_tags:
    - quarto
    - publishing
    - markdown

dependencies: []
