---
# tasks file for roles/pgadmin
- block:
  - name: install public key
    shell: |
      curl -fsS https://www.pgadmin.org/static/packages_pgadmin_org.pub | gpg --dearmor -o /usr/share/keyrings/packages-pgadmin-org.gpg
    args:
      creates: /usr/share/keyrings/packages-pgadmin-org.gpg

  - name: update source list
    shell: |
      sudo sh -c 'echo "deb [signed-by=/usr/share/keyrings/packages-pgadmin-org.gpg] https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/$(lsb_release -cs) pgadmin4 main" > /etc/apt/sources.list.d/pgadmin4.list'

  - name: apt update
    apt:
      name: pgadmin4
      update_cache: yes
      

  tags:
    - pgadmin
