---
# tasks file for roles/nodejs
- block:
  - name: install nodejs and npm
    apt:
      name:
       - nodejs
       - npm
      state: present
  - name: npm install n
    npm:
      name: n
      state: present
      global: yes
  tags:
    - nodejs
