---
# tasks file for roles/commons
- block:
  
  - name: install_common_packages
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - vim
      - vim-gtk
      - curl
      - gnome-terminal

  tags:
    - commons
