---
# tasks file for roles/commons
- block:
  
  - name: install_common_packages
    apt:
      name: "{{ item }}"
      state: latest
    with_items:
      - curl
      - unzip

  - name: update editor
    alternatives:
      name: editor
      path: /usr/bin/vim.basic

  tags:
    - commons
