---
# tasks file for roles/maven
- block:

  - name: mkdir maven
    file:
      path: /opt/maven
      state: directory

  - name: download maven
    get_url:
      url: http://ftp.riken.jp/net/apache/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz
      dest: /opt/maven

  - name: unarchive maven package
    unarchive:
      src: /opt/maven/apache-maven-3.6.3-bin.tar.gz
      dest: /opt/maven
      creates: /opt/maven/apache-maven-3.6.3/README.txt

  - name: configure alternatives
    alternatives:
      name: maven
      link: /opt/maven/default
      path: /opt/maven/apache-maven-3.6.3

  - name: configure profile.d
    template:
      src: maven.sh.j2
      dest: /etc/profile.d/maven.sh

  tags:
    - maven