---
# tasks file for roles/jan
- block:
  - name: install requirements
    apt:
      name: fuse
      state: present

  - name: mkdir Applications
    file:
      path: /home/{{ansible_env.SUDO_USER}}/Applications
      state: directory
      owner: "{{ansible_env.SUDO_USER}}"
      group: "{{ansible_env.SUDO_USER}}"

  - name: download package
    get_url:
      url: "https://github.com/janhq/jan/releases/download/v0.5.4/jan-linux-x86_64-{{jan_version}}.AppImage"
      dest: "/home/{{ansible_env.SUDO_USER}}/Applications/jan-linux-x86_64-{{jan_version}}.AppImage"
      owner: "{{ansible_env.SUDO_USER}}"
      group: "{{ansible_env.SUDO_USER}}"
      mode: 0655
  tags:
    - jan
