---
# tasks file for roles/wsl_gui
- block:

  - name: install_packages
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - git
      - build-essential
      - libssl-dev
      - libreadline-dev
      - zlib1g-dev
      - x11-apps
      - x11-utils
      - x11-xserver-utils
      - libsqlite3-dev
      - nodejs
      - fonts-ipafont
      - libxml2-dev
      - libxslt1-dev
      - language-pack-ja
      - uim
      - uim-xim
      - uim-fep
      - uim-anthy
      - dbus-x11
      - vim-gui-common
  - name: configure_DISPLAY
    lineinfile:
      path: /home/{{ ansible_env.SUDO_USER }}/.bashrc
      line: 'export DISPLAY=localhost:0.0'
      create: yes
  - name: configure_dot_uim
    template:
      src: uim.j2
      dest: /home/{{ ansible_env.SUDO_USER }}/.uim
  - name: configure_GTK_IM_MODULE
    lineinfile:
      path: /home/{{ ansible_env.SUDO_USER }}/.profile
      line: 'export GTK_IM_MODULE=uim'
      create: yes
  - name: update_locale
    shell: update-locale LANG=ja_JP.UTF-8

  tags:
    - wsl_gui
