---
# tasks file for roles/teamview

- block:

        #  - name: download teamveiwer deb
        #    get_url:
        #      url: https://download.teamviewer.com/download/linux/teamviewer_amd64.deb
        #      dest: /tmp/teamviewer_amd64.deb
  
  - name: install teamviewer
    apt:
      deb: https://download.teamviewer.com/download/linux/teamviewer_amd64.deb
      state: present

  tags:
    teamviewer
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
