- hosts: "{{ server | default('localhost') }}"
  roles:
    - register_home
    - commons
    - ipafont
    - git
    - tmux
    - pandoc
    - hexo
    - wsl_gui
    - vim
    - vim_config
    - create_links
    - intellij
    - pycharm
    - goland
    - clion
    - meson
    - pip3
    - pyenv
    - bash
