- hosts: "{{ server | default('localhost') }}"
  tasks:
    - name: start_zookeeper_server
      become: yes
      become_user: kafka
      shell: ./bin/zookeeper-server-start.sh -daemon config/zookeeper.properties
      args:
        chdir: /opt/kafka_pseudo/default
