- hosts: "{{ server | default('localhost') }}"
  tasks:
    - name: start_kafka_server
      become: yes
      become_user: kafka
      shell: ./bin/kafka-server-start.sh -daemon config/server.properties
      args:
        chdir: /opt/kafka_pseudo/default
