- hosts: "{{ server | default('localhost') }}"
  tasks:
    - name: stop_zookeeper_server
      become: yes
      become_user: kafka
      shell: ./bin/zookeeper-server-stop.sh config/zookeeper.properties
      args:
        chdir: /opt/kafka_pseudo/default
