---
# tasks file for roles/gvim
- block:

  - name: install_gvim
    apt:
      name: vim-gtk
      state: present

  tags:
    - gvim
  when: ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_major_version'] == "18"

- block:

  - name: install_gvim
    yum:
      name: vim-X11
      state: present

  tags:
    - gvim
  when: ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "7"

- block:

  - name: install_gvim
    apt:
      name: vim-gui-common
      state: present

  tags:
    - gvim
  when: ansible_facts['distribution'] == "Debian" and ansible_facts['distribution_major_version'] == "12"
