---
# tasks file for roles/hexo

- block:

  - name: install npm
    package:
      name: npm
      state: present
  - name: install hexo-cli
    npm:
      name: hexo-cli
      global: yes
  - name: install hexo-server
    npm:
      name: hexo-server
      global: yes
  - name: install hexo-deployer-git
    npm:
      name: hexo-deployer-git
      global: yes

  tags:
    - hexo
