---
# tasks file for roles/docker_for_wsl

- block:

    - name: install_requirements
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - yum-utils
    - name: add_repo
      shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    - name: install_gpg_key
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    - name: add_repository
      shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    - name: install_dockerce
      yum:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - docker-ce
        - docker-ce-cli
        - containerd.io
    - name: start_docker
      service:
        name: docker
        state: started
        enabled: yes
    - name: create_docker.sh
      template:
        src: docker.sh.j2
        dest: /etc/profile.d/docker.sh
    - name: downloads_docker-compose
      shell:  curl -L "https://github.com/docker/compose/releases/download/1.25.5/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose

  tags:
    - docker_for_wsl
