---
# tasks file for roles/docker

- block:

        #  - name: install_docker_17
        #    apt:
        #      deb: https://download.docker.com/linux/debian/dists/stretch/pool/stable/amd64/docker-ce_17.09.0~ce-0~debian_amd64.deb
        #      state: present
        #
        #  - name: start_docker
        #    service:
        #      name: docker
        #      state: started
        #      enabled: yes
    - name: install_requirements
      package:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
    - name: install_gpg_key
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    - name: add_repository
      shell: add-apt-repository -y "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    - name: install_dockerce
      package:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - docker-ce
          - docker-ce-cli
          - containerd.io
    - name: create_docker.sh
      template:
        src: docker.sh.j2
        dest: /etc/profile.d/docker.sh
    #- name: downloads_docker-compose
    #  get_url:
    #    url: https://github.com/docker/compose/releases/download/1.24.0/docker-compose-Linux-x86_64
    #    dest: /usr/local/bin/docker-compose
    #    mode: 755

  tags:
    - docker
