- hosts: "{{ server | default('fileservers') }}"
  roles:
    - geerlingguy.git
    - chusiang.vim-and-vi-mode
    - willshersystems.sshd
    - trinitronx.tmux
    - samba
    - hexo
    - anaconda
    - teamviewer
